version: "2"
linters:
  default: standard
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - revive
  exclusions:
    rules:
      - path: "_test.go"
        linters:
          - errcheck
formatters:
  enable:
    - gofmt
